

input_hmac_parameters = [
    'fiscalNumber',
    'name',
    'familyName',
    'gender',
    'identificationSerialCode',
    'identificationExpirationDate',
    'dateOfBirth',
    'nationOfBirth',
    'countyOfBirth',
    'placeOfBirth',
    'email',
    'pec',
    'countryCallingCode',
    'phoneNumber',
    'addressType',
    'addressName',
    'addressNumber',
    'addressPostalCode',
    'addressNation',
    'addressCountry',
    'addressMunicipality',
    'idCardType',
    'idCardDocNumber',
    'typeDocRelease',
    'idCardIssuer',
    'idCardIssueDate',
    'idCardExpirationDate',
]